import React, { ReactElement } from "react";
import Head from "next/head";

import { Inter } from "next/font/google";
import Home from "@/components/App/Home";
import NavLayout from "@/layouts/NavLayout";
import Announcement from "@/components/App/Home/announcement";
import Activity from "@/components/App/Home/activity";
import Enroll from "@/components/App/Home/enroll";

const inter = Inter({ subsets: ["latin"] });

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home
        activity={<Activity />}
        announcement={<Announcement />}
        enroll={<Enroll />}
      />
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <NavLayout>{page}</NavLayout>;
};

export default HomePage;
