import React, { ReactElement } from "react";
import Head from "next/head";

import { Inter } from "next/font/google";
import Home from "@/components/App/Home";
import NavLayout from "@/layouts/NavLayout";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Ký túc xá Đại Học Sài Gòn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Home />
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <NavLayout>{page}</NavLayout>;
};

export default HomePage;
