import Head from "next/head";
import React, { FC } from "react";

interface IPageHead {
  title: string;
}

const PageHead: FC<IPageHead> = (props) => {
  const { title } = props;

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.png" />
    </Head>
  );
};

export default PageHead;
